kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: influxdb-pvclaim
  namespace: kube-system 
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: managed-nfs-storage
